//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMood {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMood.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data!.
        /// </summary>
        internal static string Incorrect_data_title {
            get {
                return ResourceManager.GetString("Incorrect_data_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select audio from playlist!.
        /// </summary>
        internal static string Incorrect_select_text {
            get {
                return ResourceManager.GetString("Incorrect_select_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect select!.
        /// </summary>
        internal static string Incorrect_select_title {
            get {
                return ResourceManager.GetString("Incorrect_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio wasn&apos;t added! Please fill in all fields!.
        /// </summary>
        internal static string Not_added_aud_text {
            get {
                return ResourceManager.GetString("Not_added_aud_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist or audio wasn&apos;t found! Please select audio(*.mp3), or playlist(*.dat) from &quot;Playlists&quot; directory!.
        /// </summary>
        internal static string Not_founded_pllist_text {
            get {
                return ResourceManager.GetString("Not_founded_pllist_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist wasn&apos;t saved! Please input name of playlist!.
        /// </summary>
        internal static string Not_saved_pllist_text {
            get {
                return ResourceManager.GetString("Not_saved_pllist_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string Pausing {
            get {
                return ResourceManager.GetString("Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to played.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of aydio wasn`t found! Audio was removed from playlist!.
        /// </summary>
        internal static string Wrong_path_text {
            get {
                return ResourceManager.GetString("Wrong_path_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong path!.
        /// </summary>
        internal static string Wrong_path_title {
            get {
                return ResourceManager.GetString("Wrong_path_title", resourceCulture);
            }
        }
    }
}
